In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

In [2]:
url = "TMDB_movie_dataset_v11.csv"
df = pd.read_csv(url)
df

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121720,725719,Distance,0.000,0,Released,2014-05-07,0,1,False,NaN,...,Distance,Originally shot in 2014 w/Bolex 16mm B&W. Recu...,0.600,/fQ9eUk5hlSy4ekO1cqE7RHsZzC3.jpg,NaN,NaN,NaN,NaN,NaN,NaN
1121721,725720,Dreams,0.000,0,Released,NaN,0,2,False,NaN,...,Dreams,A conversation between a doctor and patient ab...,0.600,NaN,NaN,Drama,NaN,NaN,NaN,NaN
1121722,725721,Por Um Fio,0.000,0,Released,2003-01-01,0,0,False,NaN,...,Por Um Fio,NaN,0.600,/qUNZvyOEyTG9T7xgRosqja4KpuE.jpg,NaN,Drama,NaN,Brazil,NaN,NaN
1121723,725724,What's The Buzz?,0.000,0,Released,NaN,0,0,False,NaN,...,What's The Buzz?,"A not too gorey, masturbatory story.",0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121724,1376462,Mogitate girl: Akiko,0.000,0,Released,1985-06-01,0,57,False,NaN,...,もぎたてギャル 明子,A woman who knows she shouldn't break off her ...,0.600,NaN,NaN,NaN,Shintoho Pictures,Japan,Japanese,"softcore, pink film"

In [3]:
df=df.rename(columns={'title': 'Titulo','vote_average': 'Promedio de voto','vote_count':'Conteo de voto','release_date':'Fecha de lanzamiento',
                      'revenue':'Ingresos', 'runtime':'Duracion','adult':'Adultos',
                      'backdrop_path':'Ruta de fondo','budget':'Presupuesto','homepage':'Pagina principal',
                      'original_language':'Idioma original','original_title':'Titulo original',
                      'overview':'Descripcion','popularity':'Popularidad','poster_path': 'Ruta de poster', 'tagline': 'Eslogan', 'genres':'Genero', 'production_companies':'Productora', 'production_countries':'Pais', 'spoken_languages':'Idiomas', 'keywords':'PL'   })
df

,id,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Ruta de fondo,...,Titulo original,Descripcion,Popularidad,Ruta de poster,Eslogan,Genero,Productora,Pais,Idiomas,PL
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121720,725719,Distance,0.000,0,Released,2014-05-07,0,1,False,NaN,...,Distance,Originally shot in 2014 w/Bolex 16mm B&W. Recu...,0.600,/fQ9eUk5hlSy4ekO1cqE7RHsZzC3.jpg,NaN,NaN,NaN,NaN,NaN,NaN
1121721,725720,Dreams,0.000,0,Released,NaN,0,2,False,NaN,...,Dreams,A conversation between a doctor and patient ab...,0.600,NaN,NaN,Drama,NaN,NaN,NaN,NaN
1121722,725721,Por Um Fio,0.000,0,Released,2003-01-01,0,0,False,NaN,...,Por Um Fio,NaN,0.600,/qUNZvyOEyTG9T7xgRosqja4KpuE.jpg,NaN,Drama,NaN,Brazil,NaN,NaN
1121723,725724,What's The Buzz?,0.000,0,Released,NaN,0,0,False,NaN,...,What's The Buzz?,"A not too gorey, masturbatory story.",0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121724,1376462,Mogitate girl: Akiko,0.000,0,Released,1985-06-01,0,57,False,NaN,...,もぎたてギャル 明子,A woman who knows she shouldn't break off her ...,0.600,NaN,NaN,NaN,Shintoho Pictures,Japan,Japanese,"softcore, pink film"

In [4]:
df=df.drop(columns=['Ruta de poster', 'Eslogan', 'Ruta de fondo', 'id', 'Pagina principal'])

In [5]:
df = df.reset_index(drop=True)
df

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,Idioma original,Titulo original,Descripcion,Popularidad,Genero,Productora,Pais,Idiomas,PL
0,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,160000000,tt1375666,en,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,165000000,tt0816692,en,Interstellar,The adventures of a group of explorers who mak...,140.241,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,185000000,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,237000000,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,220000000,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,98.082,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121720,Distance,0.000,0,Released,2014-05-07,0,1,False,0,NaN,en,Distance,Originally shot in 2014 w/Bolex 16mm B&W. Recu...,0.600,NaN,NaN,NaN,NaN,NaN
1121721,Dreams,0.000,0,Released,NaN,0,2,False,0,NaN,en,Dreams,A conversation between a doctor and patient ab...,0.600,Drama,NaN,NaN,NaN,NaN
1121722,Por Um Fio,0.000,0,Released,2003-01-01,0,0,False,0,tt1148699,pt,Por Um Fio,NaN,0.600,Drama,NaN,Brazil,NaN,NaN
1121723,What's The Buzz?,0.000,0,Released,NaN,0,0,False,0,NaN,en,What's The Buzz?,"A not too gorey, masturbatory story.",0.600,NaN,NaN,NaN,NaN,NaN
1121724,Mogitate girl: Akiko,0.000,0,Released,1985-06-01,0,57,False,0,tt10209168,ja,もぎたてギャル 明子,A woman who knows she shouldn't break off her ...,0.600,NaN,Shintoho Pictures,Japan,Japanese,"softcore, pink film"

In [6]:
df.tail()

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,Idioma original,Titulo original,Descripcion,Popularidad,Genero,Productora,Pais,Idiomas,PL
1121720,Distance,0.0,0,Released,2014-05-07,0,1,False,0,NaN,en,Distance,Originally shot in 2014 w/Bolex 16mm B&W. Recu...,0.6,NaN,NaN,NaN,NaN,NaN
1121721,Dreams,0.0,0,Released,NaN,0,2,False,0,NaN,en,Dreams,A conversation between a doctor and patient ab...,0.6,Drama,NaN,NaN,NaN,NaN
1121722,Por Um Fio,0.0,0,Released,2003-01-01,0,0,False,0,tt1148699,pt,Por Um Fio,NaN,0.6,Drama,NaN,Brazil,NaN,NaN
1121723,What's The Buzz?,0.0,0,Released,NaN,0,0,False,0,NaN,en,What's The Buzz?,"A not too gorey, masturbatory story.",0.6,NaN,NaN,NaN,NaN,NaN
1121724,Mogitate girl: Akiko,0.0,0,Released,1985-06-01,0,57,False,0,tt10209168,ja,もぎたてギャル 明子,A woman who knows she shouldn't break off her ...,0.6,NaN,Shintoho Pictures,Japan,Japanese,"softcore, pink film"

In [7]:

df['Fecha de lanzamiento'].unique()

array(['2010-07-15', '2014-11-05', '2008-07-16', ..., '1965-07-06',
       '1919-08-13', '1921-07-07'], dtype=object)

In [8]:
start_date = '1895-07-07'
end_date = '2024-12-31'
date_range = pd.date_range(start=start_date, end=end_date, periods=1121724)

# Convertir las fechas a formato string
date_range_str = date_range.strftime('%Y-%m-%d')
date_range_str

Index(['1895-07-07', '1895-07-07', '1895-07-07', '1895-07-07', '1895-07-07',
       '1895-07-07', '1895-07-07', '1895-07-07', '1895-07-07', '1895-07-07',
       ...
       '2024-12-30', '2024-12-30', '2024-12-30', '2024-12-30', '2024-12-30',
       '2024-12-30', '2024-12-30', '2024-12-30', '2024-12-30', '2024-12-31'],
      dtype='object', length=1121724)

In [9]:
df['Fecha de lanzamiento'] = pd.to_datetime(df['Fecha de lanzamiento'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1121725 entries, 0 to 1121724
Data columns (total 19 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Titulo                1121712 non-null  object
 1   Promedio de voto      1121725 non-null  float64
 2   Conteo de voto        1121725 non-null  int64
 3   status                1121725 non-null  object
 4   Fecha de lanzamiento  941503 non-null   datetime64[ns]
 5   Ingresos              1121725 non-null  int64
 6   Duracion              1121725 non-null  int64
 7   Adultos               1121725 non-null  bool
 8   Presupuesto           1121725 non-null  int64
 9   imdb_id               598792 non-null   object
 10  Idioma original       1121725 non-null  object
 11  Titulo original       1121712 non-null  object
 12  Descripcion           896216 non-null   object
 13  Popularidad           1121725 non-null  float64
 14  Genero                674559 non-null   object
 15  Productora            507949 non-null   object
 16  Pais                  627546 non-null   object
 17  Idiomas               646101 non-null   object
 18  PL                    305807 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(2), int64(4), object(11)
memory usage: 155.1+ MB

In [10]:
# Extraer el año
df['año'] = df['Fecha de lanzamiento'].dt.year

# Extraer el mes
df['mes'] = df['Fecha de lanzamiento'].dt.month

# Extraer el día
df['dia'] = df['Fecha de lanzamiento'].dt.day

# Extraer el día de la semana
df['díanombre'] = df['Fecha de lanzamiento'].dt.day_name()

df.head()

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,...,Popularidad,Genero,Productora,Pais,Idiomas,PL,año,mes,dia,díanombre
0,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,160000000,tt1375666,...,83.952,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",2010.0,7.0,15.0,Thursday
1,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,165000000,tt0816692,...,140.241,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",2014.0,11.0,5.0,Wednesday
2,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,185000000,tt0468569,...,130.643,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",2008.0,7.0,16.0,Wednesday
3,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,237000000,tt0499549,...,79.932,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",2009.0,12.0,15.0,Tuesday
4,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,220000000,tt0848228,...,98.082,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",2012.0,4.0,25.0,Wednesday

In [11]:
df["status"].value_counts()

status
Released           1096891
In Production         9811
Post Production       7815
Planned               6571
Rumored                334
Canceled               303
Name: count, dtype: int64

In [12]:
df.columns

Index(['Titulo', 'Promedio de voto', 'Conteo de voto', 'status',
       'Fecha de lanzamiento', 'Ingresos', 'Duracion', 'Adultos',
       'Presupuesto', 'imdb_id', 'Idioma original', 'Titulo original',
       'Descripcion', 'Popularidad', 'Genero', 'Productora', 'Pais', 'Idiomas',
       'PL', 'año', 'mes', 'dia', 'díanombre'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1121725 entries, 0 to 1121724
Data columns (total 23 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Titulo                1121712 non-null  object
 1   Promedio de voto      1121725 non-null  float64
 2   Conteo de voto        1121725 non-null  int64
 3   status                1121725 non-null  object
 4   Fecha de lanzamiento  941503 non-null   datetime64[ns]
 5   Ingresos              1121725 non-null  int64
 6   Duracion              1121725 non-null  int64
 7   Adultos               1121725 non-null  bool
 8   Presupuesto           1121725 non-null  int64
 9   imdb_id               598792 non-null   object
 10  Idioma original       1121725 non-null  object
 11  Titulo original       1121712 non-null  object
 12  Descripcion           896216 non-null   object
 13  Popularidad           1121725 non-null  float64
 14  Genero                674559 non-null   object
 15  Productora            507949 non-null   object
 16  Pais                  627546 non-null   object
 17  Idiomas               646101 non-null   object
 18  PL                    305807 non-null   object
 19  año                   941503 non-null   float64
 20  mes                   941503 non-null   float64
 21  dia                   941503 non-null   float64
 22  díanombre             941503 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(5), int64(4), object(12)
memory usage: 189.3+ MB

In [14]:
df.isnull()

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,...,Popularidad,Genero,Productora,Pais,Idiomas,PL,año,mes,dia,díanombre
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121720,False,False,False,False,False,False,False,False,False,True,...,False,True,True,True,True,True,False,False,False,False
1121721,False,False,False,False,True,False,False,False,False,True,...,False,False,True,True,True,True,True,True,True,True
1121722,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,True,False,False,False,False
1121723,False,False,False,False,True,False,False,False,False,True,...,False,True,True,True,True,True,True,True,True,True
1121724,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [15]:
df=df.drop_duplicates()
df

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,...,Popularidad,Genero,Productora,Pais,Idiomas,PL,año,mes,dia,díanombre
0,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,160000000,tt1375666,...,83.952,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",2010.0,7.0,15.0,Thursday
1,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,165000000,tt0816692,...,140.241,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",2014.0,11.0,5.0,Wednesday
2,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,185000000,tt0468569,...,130.643,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",2008.0,7.0,16.0,Wednesday
3,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,237000000,tt0499549,...,79.932,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",2009.0,12.0,15.0,Tuesday
4,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,220000000,tt0848228,...,98.082,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",2012.0,4.0,25.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121720,Distance,0.000,0,Released,2014-05-07,0,1,False,0,NaN,...,0.600,NaN,NaN,NaN,NaN,NaN,2014.0,5.0,7.0,Wednesday
1121721,Dreams,0.000,0,Released,NaT,0,2,False,0,NaN,...,0.600,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121722,Por Um Fio,0.000,0,Released,2003-01-01,0,0,False,0,tt1148699,...,0.600,Drama,NaN,Brazil,NaN,NaN,2003.0,1.0,1.0,Wednesday
1121723,What's The Buzz?,0.000,0,Released,NaT,0,0,False,0,NaN,...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121724,Mogitate girl: Akiko,0.000,0,Released,1985-06-01,0,57,False,0,tt10209168,...,0.600,NaN,Shintoho Pictures,Japan,Japanese,"softcore, pink film",1985.0,6.0,1.0,Saturday

In [16]:
df.duplicated().sum()

0

In [17]:
lista_col=df.columns
df=df
for i in lista_col:
    df=df[df[i] != 'NaN']
df

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,...,Popularidad,Genero,Productora,Pais,Idiomas,PL,año,mes,dia,díanombre
0,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,160000000,tt1375666,...,83.952,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",2010.0,7.0,15.0,Thursday
1,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,165000000,tt0816692,...,140.241,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",2014.0,11.0,5.0,Wednesday
2,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,185000000,tt0468569,...,130.643,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",2008.0,7.0,16.0,Wednesday
3,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,237000000,tt0499549,...,79.932,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",2009.0,12.0,15.0,Tuesday
4,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,220000000,tt0848228,...,98.082,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",2012.0,4.0,25.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121720,Distance,0.000,0,Released,2014-05-07,0,1,False,0,NaN,...,0.600,NaN,NaN,NaN,NaN,NaN,2014.0,5.0,7.0,Wednesday
1121721,Dreams,0.000,0,Released,NaT,0,2,False,0,NaN,...,0.600,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121722,Por Um Fio,0.000,0,Released,2003-01-01,0,0,False,0,tt1148699,...,0.600,Drama,NaN,Brazil,NaN,NaN,2003.0,1.0,1.0,Wednesday
1121723,What's The Buzz?,0.000,0,Released,NaT,0,0,False,0,NaN,...,0.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121724,Mogitate girl: Akiko,0.000,0,Released,1985-06-01,0,57,False,0,tt10209168,...,0.600,NaN,Shintoho Pictures,Japan,Japanese,"softcore, pink film",1985.0,6.0,1.0,Saturday

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1120190 entries, 0 to 1121724
Data columns (total 23 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Titulo                1120178 non-null  object
 1   Promedio de voto      1120190 non-null  float64
 2   Conteo de voto        1120190 non-null  int64
 3   status                1120190 non-null  object
 4   Fecha de lanzamiento  941316 non-null   datetime64[ns]
 5   Ingresos              1120190 non-null  int64
 6   Duracion              1120190 non-null  int64
 7   Adultos               1120190 non-null  bool
 8   Presupuesto           1120190 non-null  int64
 9   imdb_id               598660 non-null   object
 10  Idioma original       1120190 non-null  object
 11  Titulo original       1120178 non-null  object
 12  Descripcion           895823 non-null   object
 13  Popularidad           1120190 non-null  float64
 14  Genero                674442 non-null   object
 15  Productora            507839 non-null   object
 16  Pais                  627451 non-null   object
 17  Idiomas               645986 non-null   object
 18  PL                    305719 non-null   object
 19  año                   941316 non-null   float64
 20  mes                   941316 non-null   float64
 21  dia                   941316 non-null   float64
 22  díanombre             941316 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(5), int64(4), object(12)
memory usage: 197.6+ MB

In [19]:
df[ "dia" ].fillna(df[ "dia"].mean(), inplace=True)
df[ "mes" ].fillna(df[ "mes"].mean(), inplace=True)
df[ "año" ].fillna(df[ "año"].mean(), inplace=True)	
df[ "Promedio de voto" ].fillna(df[ "Promedio de voto"].mean(), inplace=True)
df[ "Presupuesto" ].fillna(df[ "Presupuesto"].mean(), inplace=True)
df

C:\Users\yarf2\AppData\Local\Temp\ipykernel_14688\2833733956.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[ "dia" ].fillna(df[ "dia"].mean(), inplace=True)
C:\Users\yarf2\AppData\Local\Temp\ipykernel_14688\2833733956.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[ "mes" ].fillna(df[ "mes"].mean(), inplace=True)
C:\Users\yarf2\AppData\Local\Temp\ipykernel_14688\2833733956.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[ "año" ].fillna(df[ "año"].mean(), inplace=True)
C:\Users\yarf2\AppData\Local\Temp\ipykernel_14688\2833733956.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[ "Promedio de voto" ].fillna(df[ "Promedio de voto"].mean(), inplace=True)
C:\Users\yarf2\AppData\Local\Temp\ipykernel_14688\2833733956.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[ "Presupuesto" ].fillna(df[ "Presupuesto"].mean(), inplace=True)

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,...,Popularidad,Genero,Productora,Pais,Idiomas,PL,año,mes,dia,díanombre
0,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,160000000,tt1375666,...,83.952,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",2010.000000,7.00000,15.000000,Thursday
1,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,165000000,tt0816692,...,140.241,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",2014.000000,11.00000,5.000000,Wednesday
2,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,185000000,tt0468569,...,130.643,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",2008.000000,7.00000,16.000000,Wednesday
3,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,237000000,tt0499549,...,79.932,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",2009.000000,12.00000,15.000000,Tuesday
4,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,220000000,tt0848228,...,98.082,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",2012.000000,4.00000,25.000000,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121720,Distance,0.000,0,Released,2014-05-07,0,1,False,0,NaN,...,0.600,NaN,NaN,NaN,NaN,NaN,2014.000000,5.00000,7.000000,Wednesday
1121721,Dreams,0.000,0,Released,NaT,0,2,False,0,NaN,...,0.600,Drama,NaN,NaN,NaN,NaN,1999.694562,5.90706,12.769114,NaN
1121722,Por Um Fio,0.000,0,Released,2003-01-01,0,0,False,0,tt1148699,...,0.600,Drama,NaN,Brazil,NaN,NaN,2003.000000,1.00000,1.000000,Wednesday
1121723,What's The Buzz?,0.000,0,Released,NaT,0,0,False,0,NaN,...,0.600,NaN,NaN,NaN,NaN,NaN,1999.694562,5.90706,12.769114,NaN
1121724,Mogitate girl: Akiko,0.000,0,Released,1985-06-01,0,57,False,0,tt10209168,...,0.600,NaN,Shintoho Pictures,Japan,Japanese,"softcore, pink film",1985.000000,6.00000,1.000000,Saturday

In [20]:
df=df.dropna(subset=['Fecha de lanzamiento'])
df=df.dropna(subset=['díanombre'])
df=df.dropna(subset=['imdb_id'])
df=df.dropna(subset=['Descripcion'])
df=df.dropna(subset=['Genero']) 
df=df.dropna(subset=['Productora']) 
df=df.dropna(subset=['Pais']) 
df=df.dropna(subset=['Idiomas']) 
df=df.dropna(subset=['PL']) 
df

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,...,Popularidad,Genero,Productora,Pais,Idiomas,PL,año,mes,dia,díanombre
0,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,160000000,tt1375666,...,83.952,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",2010.0,7.0,15.0,Thursday
1,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,165000000,tt0816692,...,140.241,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",2014.0,11.0,5.0,Wednesday
2,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,185000000,tt0468569,...,130.643,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",2008.0,7.0,16.0,Wednesday
3,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,237000000,tt0499549,...,79.932,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",2009.0,12.0,15.0,Tuesday
4,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,220000000,tt0848228,...,98.082,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",2012.0,4.0,25.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121401,Preston's Gone,0.000,0,Released,2019-06-02,0,11,False,0,tt9546104,...,0.600,Documentary,Louisiana Public Broadcasting,United States of America,English,"police brutality, war veteran, mental health, ...",2019.0,6.0,2.0,Sunday
1121429,After the Ballot,0.000,0,Released,2008-01-01,0,89,False,0,tt3168618,...,0.600,Documentary,ONF | NFB,Canada,French,"canada, politics, quebec",2008.0,1.0,1.0,Tuesday
1121513,The Pig from Turkey,0.000,0,Released,2020-01-26,0,14,False,0,tt11024370,...,0.603,Drama,Madbunny Productions,Sweden,Swedish,"identity, racism, short film",2020.0,1.0,26.0,Sunday
1121698,Tooth 4 Tooth,0.000,0,Released,2020-05-20,0,14,False,3000,tt11985164,...,0.600,Horror,One Manner Productions,Australia,English,"vampire, gay interest, blood lust, lgbt, short...",2020.0,5.0,20.0,Wednesday
1121705,Michael Strogoff,0.000,0,Released,1910-04-01,0,0,False,0,tt0001318,...,0.856,Drama,Edison Studios,United States of America,No Language,short film,1910.0,4.0,1.0,Friday

In [21]:
df.isnull().sum()

Titulo                  0
Promedio de voto        0
Conteo de voto          0
status                  0
Fecha de lanzamiento    0
Ingresos                0
Duracion                0
Adultos                 0
Presupuesto             0
imdb_id                 0
Idioma original         0
Titulo original         0
Descripcion             0
Popularidad             0
Genero                  0
Productora              0
Pais                    0
Idiomas                 0
PL                      0
año                     0
mes                     0
dia                     0
díanombre               0
dtype: int64

In [22]:
df.fillna(method = "ffill")

C:\Users\yarf2\AppData\Local\Temp\ipykernel_14688\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,...,Popularidad,Genero,Productora,Pais,Idiomas,PL,año,mes,dia,díanombre
0,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,160000000,tt1375666,...,83.952,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",2010.0,7.0,15.0,Thursday
1,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,165000000,tt0816692,...,140.241,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",2014.0,11.0,5.0,Wednesday
2,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,185000000,tt0468569,...,130.643,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",2008.0,7.0,16.0,Wednesday
3,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,237000000,tt0499549,...,79.932,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",2009.0,12.0,15.0,Tuesday
4,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,220000000,tt0848228,...,98.082,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",2012.0,4.0,25.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121401,Preston's Gone,0.000,0,Released,2019-06-02,0,11,False,0,tt9546104,...,0.600,Documentary,Louisiana Public Broadcasting,United States of America,English,"police brutality, war veteran, mental health, ...",2019.0,6.0,2.0,Sunday
1121429,After the Ballot,0.000,0,Released,2008-01-01,0,89,False,0,tt3168618,...,0.600,Documentary,ONF | NFB,Canada,French,"canada, politics, quebec",2008.0,1.0,1.0,Tuesday
1121513,The Pig from Turkey,0.000,0,Released,2020-01-26,0,14,False,0,tt11024370,...,0.603,Drama,Madbunny Productions,Sweden,Swedish,"identity, racism, short film",2020.0,1.0,26.0,Sunday
1121698,Tooth 4 Tooth,0.000,0,Released,2020-05-20,0,14,False,3000,tt11985164,...,0.600,Horror,One Manner Productions,Australia,English,"vampire, gay interest, blood lust, lgbt, short...",2020.0,5.0,20.0,Wednesday
1121705,Michael Strogoff,0.000,0,Released,1910-04-01,0,0,False,0,tt0001318,...,0.856,Drama,Edison Studios,United States of America,No Language,short film,1910.0,4.0,1.0,Friday

In [27]:
df.tail()

,Titulo,Promedio de voto,Conteo de voto,status,Fecha de lanzamiento,Ingresos,Duracion,Adultos,Presupuesto,imdb_id,...,Popularidad,Genero,Productora,Pais,Idiomas,PL,año,mes,dia,díanombre
1121401,Preston's Gone,0.0,0,Released,2019-06-02,0,11,False,0,tt9546104,...,0.600,Documentary,Louisiana Public Broadcasting,United States of America,English,"police brutality, war veteran, mental health, ...",2019.0,6.0,2.0,Sunday
1121429,After the Ballot,0.0,0,Released,2008-01-01,0,89,False,0,tt3168618,...,0.600,Documentary,ONF | NFB,Canada,French,"canada, politics, quebec",2008.0,1.0,1.0,Tuesday
1121513,The Pig from Turkey,0.0,0,Released,2020-01-26,0,14,False,0,tt11024370,...,0.603,Drama,Madbunny Productions,Sweden,Swedish,"identity, racism, short film",2020.0,1.0,26.0,Sunday
1121698,Tooth 4 Tooth,0.0,0,Released,2020-05-20,0,14,False,3000,tt11985164,...,0.600,Horror,One Manner Productions,Australia,English,"vampire, gay interest, blood lust, lgbt, short...",2020.0,5.0,20.0,Wednesday
1121705,Michael Strogoff,0.0,0,Released,1910-04-01,0,0,False,0,tt0001318,...,0.856,Drama,Edison Studios,United States of America,No Language,short film,1910.0,4.0,1.0,Friday